version: '2.1'
services:

    go:
        build: .
        ports:
            - "8000:8000"
        links:
            - postgres
        depends_on:
          postgres:
            condition: service_healthy
        environment:
            user: 'hello'
            password: 'hello'
            host: 'postgres'
            charset: 'UTF-8'
            port: '8000'
            dbname: 'hello'

    postgres:
        image: onjin/alpine-postgres:9.5
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hello
            POSTGRES_PASSWORD: hello
            POSTGRES_DB: hello
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "hello"]
            interval: 5s
            retries: 20
            timeout: 2s